/**
 * Agent payment/subscription system (PR 2).
 *
 * Design notes:
 * - `packages` is a GLOBAL/platform table, not tenant-scoped — same pattern
 *   as the existing `plans` table (migration 20260708_01): Plotra itself
 *   sets a fixed catalog of agent packages, managed by super-admin, not by
 *   individual tenant owners. No RLS needed for the same reason `plans`
 *   has none — it isn't tenant data.
 * - New `users` columns default to values that make every EXISTING agent
 *   row (and every future insert through any of the three places a `users`
 *   row gets created — self-registration owner-approval, self-registration
 *   admin-approval, or the older direct-invite flow) behave exactly as
 *   before this migration: unpaid, no package chosen yet, free to keep
 *   listing. Nothing is retroactively blocked.
 * - `payment_submissions` IS tenant-scoped (an agent's payment relates to
 *   their specific tenant) with the same RLS shape as `pending_agent_signups`
 *   (migration 20260827_01) — tenant-owner and service-context (super-admin
 *   review, webhook receipt intake) both need access, nothing else should.
 */

exports.up = async function (knex) {
  await knex.schema.createTable('packages', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('uuid_generate_v4()'));
    table.string('name', 100).notNullable();
    table.integer('amount_inr').notNullable();
    table.string('qr_code_url', 500).nullable(); // static, pre-generated per package — admin-provided, not generated by the app
    table.boolean('is_active').notNullable().defaultTo(true);
    table.integer('sort_order').notNullable().defaultTo(0); // display order in the WhatsApp package-selection menu
    table.timestamps(true, true);
  });

  await knex.schema.alterTable('users', (table) => {
    table.uuid('package_id').nullable().references('id').inTable('packages').onDelete('SET NULL');
    // Cycle anchor date — defaults to now() so it backfills every existing
    // agent row at migration time (and every future row via the column
    // default) as "onboarded today," rather than leaving it null and
    // needing a separate backfill pass or per-insert-site plumbing.
    table.timestamp('onboarded_at').notNullable().defaultTo(knex.fn.now());
    table.string('payment_status', 20).notNullable().defaultTo('unpaid'); // unpaid | pending_review | paid
    table.boolean('can_add_listing').notNullable().defaultTo(true);
    // Short-lived conversational state flag: set when an agent texts a
    // payment-intent keyword ("payment"/"receipt"/"bhugtan" — see
    // agentPaymentService.js), cleared the moment their next photo is
    // captured as a receipt submission (or they send something else,
    // which silently drops it — see webhookController.js). Not part of
    // the spec's literal schema list, added because the receipt-photo
    // trigger needs *some* way to distinguish a receipt photo from a
    // property-listing photo, and this is the narrowest, least invasive
    // signal — an explicit keyword the agent typed, not a heuristic.
    table.boolean('awaiting_receipt_submission').notNullable().defaultTo(false);
  });

  await knex.schema.createTable('payment_submissions', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('uuid_generate_v4()'));
    table.uuid('tenant_id').notNullable().references('id').inTable('tenants').onDelete('CASCADE');
    table.uuid('agent_id').notNullable().references('id').inTable('users').onDelete('CASCADE');
    table.string('receipt_photo_url', 500).notNullable();
    table.integer('amount_inr').nullable(); // agent-claimed amount if ever collected as text; null when only the photo is available
    table.timestamp('submitted_at').notNullable().defaultTo(knex.fn.now());
    table.string('status', 20).notNullable().defaultTo('pending'); // pending | approved | rejected
    table.uuid('reviewed_by').nullable().references('id').inTable('users').onDelete('SET NULL');
    table.timestamp('reviewed_at').nullable();
    table.timestamps(true, true);

    table.index(['tenant_id', 'status'], 'idx_payment_submissions_tenant_status');
    table.index(['agent_id'], 'idx_payment_submissions_agent');
  });

  await knex.raw(`ALTER TABLE payment_submissions ENABLE ROW LEVEL SECURITY`);
  await knex.raw(`ALTER TABLE payment_submissions FORCE ROW LEVEL SECURITY`);
  await knex.raw(`
    CREATE POLICY payment_submissions_tenant_isolation_select
      ON payment_submissions
      FOR SELECT
      USING (is_service_context() OR tenant_id = current_tenant_id())
  `);
  await knex.raw(`
    CREATE POLICY payment_submissions_tenant_isolation_write
      ON payment_submissions
      FOR ALL
      USING (is_service_context() OR tenant_id = current_tenant_id())
      WITH CHECK (is_service_context() OR tenant_id = current_tenant_id())
  `);
};

exports.down = async function (knex) {
  await knex.raw(`DROP POLICY IF EXISTS payment_submissions_tenant_isolation_select ON payment_submissions`);
  await knex.raw(`DROP POLICY IF EXISTS payment_submissions_tenant_isolation_write ON payment_submissions`);
  await knex.schema.dropTableIfExists('payment_submissions');

  await knex.schema.alterTable('users', (table) => {
    table.dropColumn('package_id');
    table.dropColumn('onboarded_at');
    table.dropColumn('payment_status');
    table.dropColumn('can_add_listing');
    table.dropColumn('awaiting_receipt_submission');
  });

  await knex.schema.dropTableIfExists('packages');
};
